# Generated by Django 6.0.7 on 2026-08-01 21:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_tickets', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], db_index=True, default='active', max_length=20)),
                ('draw_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('featured', models.BooleanField(default=False)),
                ('social_aid_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('winner_ticket_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ayuda social',
                'verbose_name_plural': 'Ayudas sociales',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_numbers', models.JSONField(default=list)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=50)),
                ('buyer_country', models.CharField(choices=[('CU', 'Cuba'), ('US', 'EE.UU.')], default='CU', max_length=2)),
                ('buyer_province', models.CharField(blank=True, max_length=100)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Confirmado'), ('expired', 'Vencido')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField()),
                ('winner_name', models.CharField(max_length=200)),
                ('winner_phone', models.CharField(blank=True, max_length=50)),
                ('winner_province', models.CharField(blank=True, max_length=100)),
                ('prize', models.CharField(blank=True, max_length=200)),
                ('drawn_at', models.DateTimeField()),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_photo', models.URLField(blank=True)),
                ('delivery_video', models.URLField(blank=True)),
                ('raffle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Ganador',
                'verbose_name_plural': 'Ganadores',
                'ordering': ['-drawn_at'],
            },
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_raffles', to='raffles.winner'),
        ),
    ]
